import RegisterForm from "@/components/register-form";
import Head from "next/head";

export default function Register() {
  return (
    <>
      <Head>
        <title>Authentication - Register</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <RegisterForm />
      </main>
    </>
  );
}
